### ISSUE TITLE
TODO (rules) for 0.0.2

### ISSUE THREAD

**Issue by oriSomething** [HappySale/eslint-plugin-parse#1]
- [x] prefer-parse-promise
- [x] no-parse-promise-assign
- [x] no-slow-query
- [x] no-not-query
- [x] no-promise-always
### Maybe
- no-count-query
### Canceled
- no-underscore-attribute - problematic to apply the rule and Cloud Code will throw anyway

**Comment by oriSomething** [comment]
prefer-parse-promise b11e11cd92fda8f378b52d82cdf74501c65a3756

**Comment by oriSomething** [comment]
no-parse-promise-assign e72ab806747093676de54df746407853b29a48c5

**Comment by oriSomething** [comment]
- no-slow-query d4bf7851704a44381826115e67ba3574a46ce567
- no-not-query 017bf6663d8eac86e11b8b79775f0c98d1f5b40d
- no-promise-always f25e6113a0dc1ade54b0d8d8b22f4b6f05253be4
