### ISSUE TITLE
TODO (rules) for next version

### ISSUE THREAD

**Issue by oriSomething** [HappySale/eslint-plugin-parse#2]
- [ ] no-complex-count-query - allow only simple count query
- [ ] limit-range - valid limit range
- [ ] skip-range - valid skip range
- [ ] underscore-objects - fix 'User' - > '_User', 'Installation' -> '_Installation' 
## optional
- no-promise-always - (option to disable if it's last function)
- no-not-query - (simplify checker for performance)
- no-slow-query - (simplify checker for performance)
